name: Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - packages/**
      - tsconfig.json

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Tests
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16.14', '16', '18']
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048 # v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Installation
        run: yarn
      - name: Test
        run: yarn test
      - name: TypeCheck website
        run: yarn workspace website typecheck
